# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'My Sonarcloud'
    organization: 't00212237'
    scannerMode: 'Other'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: Docker@2
  inputs:
    containerRegistry: 'My Docker Hub'
    repository: 'bigguy123 / spring-petclinic'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'SNAPSHOT-3.0.0'
- task: Docker@2
  inputs:
    containerRegistry: 'My Docker Hub'
    repository: 'bigguy123 / spring-petclinic'
    command: 'push'
    tags: 'SNAPSHOT-3.0.0'